In [26]:
import pandas as pd
import numpy as np

In [36]:
fpath = '../data/expt1.txt'
# fpath = '../data/inputpt1.txt'

arr = []
xp = 0  # x-position of guard and
yp = 0  # y-position 
with open(fpath, 'r') as f:
    lines = f.readlines()
    for i, line in enumerate(lines):
        if '^' in line:
            yp = i
            xp = line.index('^')
            
        arr.append(list(line[:-1]))
gp = xp, yp  # guard position
gp

(4, 6)

In [35]:
df = pd.DataFrame(arr)
df

   0  1  2  3  4  5  6  7  8  9
0  .  .  .  .  #  .  .  .  .  .
1  .  .  .  .  .  .  .  .  .  #
2  .  .  .  .  .  .  .  .  .  .
3  .  .  #  .  .  .  .  .  .  .
4  .  .  .  .  .  .  .  #  .  .
5  .  .  .  .  .  .  .  .  .  .
6  .  #  .  .  ^  .  .  .  .  .
7  .  .  .  .  .  .  .  .  #  .
8  #  .  .  .  .  .  .  .  .  .
9  .  .  .  .  .  .  #  .  .  .